services:
  - type: web
    name: object-detection-app
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_ENV
        value: production
