services:
  - type: web
    name: object-detection-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --timeout 300 --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_ENV
        value: production
